# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tblog
  seed: 1337

checkpoint:
  save_interval: 1
  save_interval_updates: 2000
  keep_interval_updates: 1
  #keep_best_checkpoints: 5
  no_epoch_checkpoints: true
  best_checkpoint_metric: loss

distributed_training:
  ddp_backend: no_c10d
  distributed_backend: 'nccl'
  find_unused_parameters: true
  distributed_world_size: 1
  #distributed_port: 29671
  nprocs_per_node: 8

task:
  _name: hubert_pretraining
  data: ???
  fine_tuning: true
  label_dir: ???
  normalize: false  # must be consistent with pre-training
  labels: ["phn"]
  single_target: true
  max_sample_size: 250000  # 这个是实际训练时最大的chunk_size，超长音频会被切分, 只留下一个chunk用于训练
  # max_keep_size: 320000  # 这个是保留音频的最大采样点数，超过的音频不参与训练
  min_sample_size: 16000  # 这个是保留音频的最小采样点数，低于的音频不参与训练
  pad_audio: false
  random_crop: true

dataset:
  num_workers: 0
  max_tokens: 1400000
  validate_after_updates: ${model.freeze_finetune_updates}
  validate_interval: 1
  validate_interval_updates: 10000
  train_subset: train
  valid_subset: valid

criterion:
  _name: label_smoothed_cross_entropy
  label_smoothing: 0.1
  report_accuracy: true

optimization:
  max_update: 1000000
  lr: [2e-4]
  clip_norm: 10.0
  sentence_avg: false
  update_freq: [8]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 8000

model:
  _name: hubert_ctc
  w2v_path: ???
  apply_mask: false
  mask_selection: static
  mask_length: 10
  mask_other: 0
  mask_prob: 0.75
  mask_channel_selection: static
  mask_channel_length: 64
  mask_channel_other: 0
  mask_channel_prob: 0.5
  layerdrop: 0.1
  dropout: 0.0
  activation_dropout: 0.1
  attention_dropout: 0.0
  feature_grad_mult: 0.0   #设为小于等于0的数，使得cnn_extractor被冻结
  no_pretrained_weights: false
  freeze_finetune_updates: 0

hydra:
  job:
    config:
      override_dirname:
        kv_sep: '-'
        item_sep: '__'
        exclude_keys:
          - run
          - task.data
          - task.label_dir
          - model.w2v_path
          - dataset.train_subset
          - dataset.valid_subset
          - criterion.wer_kenlm_model
          - criterion.wer_lexicon
  run:
    dir: ???
  sweep:
    dir: ???
    subdir: ${hydra.job.config_name}__${hydra.job.override_dirname}
